### ISSUE TITLE
Is it compatible with IE8？

### ISSUE THREAD

**Issue by TanTouJunJun** [SME-FE/vue-light-timeline#10]
thank you for your code, it worked in my project!
but, I don't sure, Is it compatible with IE8?

**Comment by hwen** [comment]
It depend on vue2 Compatibility.

> Vue does not support IE8 and below, because it uses ECMAScript 5 features that are un-shimmable in IE8. However it supports all ECMAScript 5 compliant browsers.

[Vue.js Compatibility Note](https://vuejs.org/v2/guide/installation.html#Compatibility-Note)
