### ISSUE TITLE
Enable htmlMode for tag

### ISSUE THREAD

**Issue by hija** [SME-FE/vue-light-timeline#11]
Hey there,

I think it would be a great addition to add htmlMode for the tag, too. In my case I would like to do a line break between date and time in my tag. When I try to use HTML (e.g. <p>, <div>, <span>, ...) the tag does not seem to accept it. Since we already have the htmlMode for the content parameter, I think it would be great to enable it for the tag parameter, too.

Best
Hilko

**Comment by hwen** [comment]
try using slot
```html
<template slot='tag' slot-scope='{ item }'>
      <div>your html code</div>
</template>
```
