### ISSUE TITLE
HTML Usage

### ISSUE THREAD

**Issue by bart** [SME-FE/vue-light-timeline#4]
Hey,

is it also possible to use HTML instead of just simple text somehow?

Thanks!

**Comment by hwen** [comment]
Hi, bart.
Do you means insert HTML string as content ?  
```js
items: [
        {
          tag: '2018-01-12',
          content: '<b>hi</b>'
        }
 ]
```

**Comment by bart** [comment]
Exactly, yes. If I do it the way you described it I'm getting back the plain HTML in timeline elements. So for example `<b>My text</b>` isn't bold but its the HTML representation `<b>My text</b>`.

**Comment by hwen** [comment]
I had added `htmlMode` option for this feature and released it in the new version.

Now, we can do something like

```js
{
  type: 'star',
  tag: '2018-01-14',
  htmlMode: true,
  content: `<div style="color: red;"> hi </div>`
}
```
cause it may lead to [XSS problem](https://vuejs.org/v2/guide/syntax.html#Raw-HTML) by using `v-html` , so  it is disable by default.

**Comment by bart** [comment]
Awesome, thank you so much @hwen ! That's amazing 🎉
