### ISSUE TITLE
Add slots

### ISSUE THREAD

**Issue by vratojr** [SME-FE/vue-light-timeline#5]
Hello! 
Nice timeline,
could add slots for the date, icon and text so they can be easily customizable?

**Comment by hwen** [comment]
Look Good! Great~
BTW.
Could you update the doc too, which is the README.md file?
So that other people will know the update.

**Comment by vratojr** [comment]
Here you are :)

**Comment by hwen** [comment]
I had merged your code, added new [exmaple](https://sme-fe.github.io/vue-light-timeline/#/slot) and release it in the `1.0.1` version.

But I changed the slot name keyword from `text` to `content`, because it's little confuse and non-consistency, hope you don't mind.

**Comment by vratojr** [comment]
I don't mind at all, great job :)
