### ISSUE TITLE
CDN of source code?

### ISSUE THREAD

**Issue by greeven** [SME-FE/vue-light-timeline#7]
I was wondering if there is a possibility to embed this repo directly in an html file with something like `<script src="https://cdn-tosomewhere/file.js"></script>`.

Would that be possible?

**Comment by hwen** [comment]
NPM packages would sync to unpkg, so you can

```
https://unpkg.com/vue-light-timeline
```

**Comment by greeven** [comment]
Awesome, thank you! For those interested:

**Implement with:**
```
<script src="https://unpkg.com/vue-light-timeline@1.0.1/index.js"></script>
```

**Adding component:**
```
<script>
  Vue.component('light-timeline', vueLightTimeline.Timeline)

  const theme = 'red';

  var app = new Vue({
    el: '#app',
  ...
```
